server:
  port: 9090

spring:
  profiles: dev
  application:
    name: spring-boot-project
    version: 1.0.0
  output.ansi.enabled: always

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-study?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    password: root
    username: root

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000           # 连接超时时间（毫秒）
    database: 0
    lettuce:
      pool:
        max-active: 8    # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8      # 连接池中的最大空闲连接 默认 8
        min-idle: 0      # 连接池中的最小空闲连接 默认 0
  cache:
    type: redis   # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配

  # 扫描的包路径,默认扫描所有
  swagger:
    base-package: com.xiaojiangtun
    enabled: true    #默认为true

  #rabbitmq
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    listener.simple.acknowledge-mode: manual  # 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none

########## Mybatis 自身配置 ##########
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xiaojiangtun.entity
  # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  configuration.map-underscore-to-camel-case: true

########## 通用Mapper ##########
# 主键自增回写方法,默认值MYSQL,详细说明请看文档
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: true  # 设置 insert 和 update 中，是否判断字符串类型!=''
  enum-as-simple-type: true  # 枚举按简单类型处理

########## 分页插件 ##########
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true



default:
  age: ${random.int(10)}
  name: fudayu

# error < warning < info < debug
logging:
  file: d:/logs/${spring.application.name}.log
  file.max-size: 512MB
  file.max-history: 30

  level:
    root: info
    org.springframework.web: debug
    org.hibernate: error


