server:
  port: 9090

spring:
  profiles: dev
  application:
    name: spring-boot-project
    version: 1.0.0
  output.ansi.enabled: always

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-study?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    password: root
    username: root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xiaojiangtun.entity
  # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  configuration.map-underscore-to-camel-case: true

default:
  age: ${random.int(10)}
  name: fudayu

# error < warning < info < debug
logging:
  file: d:/logs/${spring.application.name}.log
  file.max-size: 512MB
  file.max-history: 30

  level:
    root: info
    org.springframework.web: debug
    org.hibernate: error


